# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docs', models.FileField(upload_to=document.models.Document.generate_filename)),
                ('status', models.CharField(choices=[('서명 전', '서명 전'), ('내 서명 필요', '내 서명 필요'), ('상대 서명 필요', '상대 서명 필요'), ('완료', '완료'), ('거절', '거절'), ('취소', '취소')], max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_myself', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Folder'),
        ),
        migrations.AddField(
            model_name='document',
            name='parters',
            field=models.ManyToManyField(related_name='docs_by_partners', to=settings.AUTH_USER_MODEL),
        ),
    ]
