# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20180118_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='parters',
            new_name='partners',
        ),
    ]
