# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20180120_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=140),
            preserve_default=False,
        ),
    ]
