# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20180121_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='filepath',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
